---
- name : Gather all registered virtual machines
  hosts: localhost

  tasks:
  - name: Gather all registered virtual machines
    vmware_vm_facts:
      hostname: vc65.labvmware.local
      username: administrator@vsphere.local
      password: 
      validate_certs: no
    delegate_to: localhost
    register: vmfacts
